[server]
GUILD=1125730669406998618

[roles]
MODERATORS=1125756054001684560
ORGANISERS=1125756245626863697
VOLUNTEERS=1125756316942602400
SPEAKERS=1125756357820289024
SPONSORS=1125756395409649706
PARTICIPANTS=1125756876546646097
PARTICIPANTS_REMOTE=1125757073154646106

[registration]
REG_CHANNEL_ID=1125911236857573486
REG_HELP_CHANNEL_ID=1125755854478651392
REG_LOG_CHANNEL_ID=1125755915526742077

[eventbrite]
TICKET_TO_ROLES_JSON = "ticket_to_roles_prod.json"

[logging]
LOG_LEVEL = "INFO"

[programme_notifications]
timezone = "Atlantic/Canary"
timewarp = false
conference_days_first = "2023-10-06"
conference_days_last = "2023-10-08"
pretalx_schedule_url = "https://pretalx.com/api/events/pycones-2023/schedules/latest/"
europython_session_base_url = "https://charlas.2023.es.pycon.org/pycones-2023/talk/{slug}"
europython_api_session_url = "https://charlas.2023.es.pycon.org/api/session/{code}"

[[programme_notifications.notification_channels]]
webhook_id = "PYTHON_DISCORD"
include_channel_in_embeds = false

[[programme_notifications.notification_channels]]
webhook_id = "PROGRAMME_NOTIFICATIONS"
include_channel_in_embeds = true

[programme_notifications.rooms.2189]
# Forum Hall
webhook_id = "ROOM_2189"
discord_channel_id = "1120780288755253338"
